---
name: Main Branch Merge & FTP Copy
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's a merge to main
        run: >
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" ==
          "refs/heads/main" ]; then
            echo "Branch is 'main', proceeding..."
          else
            echo "Branch is not 'main', exiting..."
            exit 0
          fi
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: FTP transfer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/archive/**
            README.md
